spring:
  application:
    name: api-gateway

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:9000/eureka
  instance:
    prefer-ip-address: true

zuul:
  prefix: /api
  routes:
    cat-service:
      path: /cat-service/**
      serviceId: CAT-SERVICE
      sensitiveHeaders:
    user-service:
      path: /user-service/**
      serviceId: USER-SERVICE
    auth-service:
      path: /auth-service/**
      serviceId: AUTH-SERVICE

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
ribbon:
  ReadTimeout: 5000