spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password2
    url: jdbc:postgresql://db:5432/java-lab-practice
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  jta:
    enabled: true
  redis:
    host: redis
    port: 6379

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:9000/eureka
  instance:
    prefer-ip-address: true

jwt:
  header: Authorization
  secret: semyon_secret
  expiration: 120000 #milliseconds